development:
  FACEBOOK_PAGE_ACCESS_TOKEN: EAATfxVZALlQsBAAutyyDgLtp9eBprrWfCOSVZBMXruDvPjdqq3a0xXXkGphoerAc7yBt3Vpq7hxfuXlnTJ02bO0AvbqK7NsL1eVPK8sJdfARqabvZAoR5YKOsLG7xhZCHeFZCZCvdY8s3S6ZApcPYSRykJpOGk2W0kZC03wtW2SS6gZDZD
production:
    FACEBOOK_PAGE_ACCESS_TOKEN: EAATfxVZALlQsBAAutyyDgLtp9eBprrWfCOSVZBMXruDvPjdqq3a0xXXkGphoerAc7yBt3Vpq7hxfuXlnTJ02bO0AvbqK7NsL1eVPK8sJdfARqabvZAoR5YKOsLG7xhZCHeFZCZCvdY8s3S6ZApcPYSRykJpOGk2W0kZC03wtW2SS6gZDZD
